server:
  port: 8000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///jyxdb?characterEncoding=utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
